export const easterEggs: Record<string, string> = {
  search: "Search across files? Sir, this is a portfolio. There are like 6 files. Just... look.",
  sourceControl: "14 commits. 2 of them are 'fix fix fix'. The rest are 'final final FINAL'. We don't talk about it.",
  debug: "No bugs here. (The bugs are in production, where they belong.)",
  extensions: "Extensions marketplace coming soon\u2122. Currently accepting applications from: dark mode, prettier, and existential dread.",
  settings: "Settings.json has been corrupted by 3 AM coding sessions. We're working on recovery.",
  package_json: '{ "scripts": { "panic": "rm -rf node_modules && npm install" } }',
  gitignore: "node_modules/ -- the black hole of every project. 287MB of regret.",
  tsconfig: "strict: true -- Because I enjoy suffering.",
  tailwind_config: "This file is 40% config, 60% copy-pasted from Stack Overflow.",
  readme: "You are currently reading the site that this readme describes. Meta.",
  breadcrumb: "You clicked the breadcrumbs. Bold move. Nothing happens. But I respect the curiosity.",
  status_ln_col: "Ln 1, Col 1 -- You're at the beginning. Aren't we all.",
  status_errors: "No errors, no warnings. (Because I disabled the linter before pushing).",
  status_spaces: "Spaces: 2. If you use tabs, please close this window.",
  status_encoding: "UTF-8. The only encoding that matters.",
  status_filetype: "It's React. It's always React.",
  resume_missing: "resume.pdf not found. The developer is... still writing it. We're all in progress.",
  components_dir: "These are the components powering this very page. It's components all the way down.",
};
